import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, relative } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const asset = join(root, "src/web/client-bundle.generated.ts");
const digest = (value: string) => createHash("sha256").update(value).digest("hex");

function sourceIdentity(): string {
  const files = ["scripts/build-web.ts", "tsconfig.browser.json"];
  for (const file of readdirSync(join(root, "src/web"))) {
    if (/^client-.*\.ts$/.test(file) && !["client-script.ts", "client-bundle.generated.ts"].includes(file)) files.push("src/web/" + file);
  }
  function browserFiles(directory: string) {
    for (const file of readdirSync(join(root, directory), { withFileTypes: true })) {
      const path = directory + "/" + file.name;
      if (file.isDirectory()) browserFiles(path);
      else if (/\.[jt]s$/.test(path)) files.push(path);
    }
  }
  browserFiles("src/web/browser");
  return digest(JSON.stringify(files.sort().map(path => [path, readFileSync(join(root, path), "utf8").replace(/\r\n/g, "\n")])));
}

export function checkWebClient(): void {
  let current: string;
  try { current = readFileSync(asset, "utf8").replace(/\r\n/g, "\n"); }
  catch { throw new Error("Browser asset is missing. Run bun run build:web."); }
  const match = current.match(/^\/\/ Generated by bun run build:web\. Do not edit\.\n\/\/ sources: ([a-f0-9]{64})\n\/\/ bundle: ([a-f0-9]{64})\nexport const WEB_CLIENT_BUNDLE = ([\s\S]+);\n$/);
  if (!match || match[1] !== sourceIdentity() || digest(JSON.parse(match[3]!)) !== match[2]) {
    throw new Error("Browser asset is stale or modified. Run bun run build:web, then include the regenerated asset.");
  }
}

export async function buildWebClient(): Promise<void> {
  const result = await Bun.build({
    entrypoints: [join(root, "src/web/browser/entry.ts")],
    root, target: "browser", format: "iife", minify: false, sourcemap: "none",
    plugins: [{ name: "browser-runtime-only", setup(build) {
      build.onResolve({ filter: /^(?:node:|bun(?::|$))/ }, args => { throw new Error("Server runtime import in browser graph: " + args.path); });
      build.onLoad({ filter: /\.[cm]?[jt]s$/ }, args => {
        const path = relative(root, args.path).replaceAll("\\", "/");
        if (!(path.startsWith("src/web/browser/") || /^src\/web\/client-.*\.ts$/.test(path))
          || ["src/web/client-script.ts", "src/web/client-bundle.generated.ts"].includes(path)) throw new Error("Unexpected runtime dependency in browser graph: " + path);
        return undefined;
      });
    } }],
  });
  if (!result.success) throw new AggregateError(result.logs, "Browser build failed.");
  if (result.outputs.length !== 1) throw new Error("The Web console requires one self-contained browser bundle.");
  const code = (await result.outputs[0]!.text()).replace(/<\//g, "<\\/");
  const content = "// Generated by bun run build:web. Do not edit.\n// sources: " + sourceIdentity()
    + "\n// bundle: " + digest(code) + "\nexport const WEB_CLIENT_BUNDLE = " + JSON.stringify(code) + ";\n";
  let previous = "";
  try { previous = readFileSync(asset, "utf8"); } catch { /* First build. */ }
  if (previous !== content) writeFileSync(asset, content);
}

if (import.meta.main) {
  if (process.argv.includes("--check")) checkWebClient();
  else await buildWebClient();
}
