export const IMPACT_APPLE_TEXT = {
  zh: {
    "apple.lessons":"这次出现的经验", "apple.taskCounts":"{searches} 次检索 · {exposures} 次展示",
    "apple.rated":"已明确评价的经验展示",
    "apple.overview":"成效概览", "apple.runs":"任务记录", "apple.improve":"改进工作台", "apple.verify":"验证",
    "apple.overviewCopy":"看看经验是否有用，知道下一步改哪里。", "apple.runsCopy":"把当时的证据和现在的判断，放在一起。",
    "apple.improveCopy":"从一次具体反馈出发，把经验改到更合适。", "apple.verifyCopy":"每一次改动，都有可以回看的依据。",
    "apple.all":"全部", "apple.pending":"待反馈", "apple.attention":"需要关注", "apple.search":"搜索任务或工具", "apple.loaded":"已加载 {count} 条任务",
    "apple.noMatches":"没有符合条件的记录。", "apple.allTime":"全部时间", "apple.project":"当前项目", "apple.connections":"观测连接",
    "apple.confirm":"确认问题", "apple.edit":"修改经验", "apple.test":"验证并应用", "apple.nextEdit":"修改这条经验", "apple.nextTest":"下一步：验证",
    "apple.back":"返回", "apple.unsaved":"草稿保留在当前页面，切换区域不会丢失。未保存内容在刷新前会提示。",
    "apple.original":"当前基础版本", "apple.draft":"修订草稿", "apple.examples":"适用的例子与不适用的反例", "apple.saved":"草稿已保存",
    "apple.sources":"问题来自哪里", "apple.sourceCopy":"先看反馈发生的上下文，再决定如何修改经验。", "apple.openRun":"查看来源任务",
    "apple.issue":"这条经验需要检查适用范围", "apple.issueCount":"{count} 条反馈指向同一版本", "apple.miss":"一条经验没有在需要时出现",
    "apple.missCopy":"查询正文没有被记录。补充当时的检索方式，审阅后收录为评测例子。", "apple.reviewMiss":"补充检索例子",
    "apple.pendingWork":"待处理", "apple.completedWork":"已完成", "apple.noWork":"还没有待处理的改进", "apple.noWorkCopy":"在任务里记录反馈后，问题与修订会集中到这里。",
    "apple.noRevisions":"还没有经验验证记录", "apple.noRevisionsCopy":"从任务反馈创建修订，补充正反例，再查看真实的检索验证结果。",
    "apple.inspect":"查看经验", "apple.inspectCopy":"只展示与当时版本一致的内容。", "apple.inspectMissing":"这个历史版本的正文不可用。可以查看来源标识及当前经验，不能把当前内容当作当时证据。",
    "apple.query":"当时在找什么", "apple.queryMissing":"此记录没有保留查询正文。检索结果与经验版本证据仍然可查看。",
    "apple.noQuery":"尚未收到检索事件。", "apple.runName":"{client} · {date}", "apple.runUnnamed":"未记录任务名称", "apple.runCopy":"{searches} 次检索 · {exposures} 次经验展示 · {feedback} 条反馈事件",
    "apple.openImprove":"查看并改进", "apple.pendingTitle":"还有经验展示没有反馈", "apple.pendingCopy":"回顾当时的任务，补充一次明确的判断。",
    "apple.followTitle":"继续观察经验的实际使用", "apple.followCopy":"有新的任务反馈后，再判断经验是否需要调整。", "apple.done":"已完成的改进",
    "apple.waiting":"待观察", "apple.later":"关联版本的后续任务", "apple.helpful":"反馈认为有帮助", "apple.boundary":"检索通过不等于实际任务改善。只统计明确关联到该版本的后续证据。",
    "apple.recent":"最近的任务", "apple.viewAll":"查看全部", "apple.change":"经验改动", "apple.retrieval":"检索对照与用例",
    "apple.changed":"有变化", "apple.failed":"未通过", "apple.noChanges":"没有符合筛选条件的用例。", "apple.positive":"正例", "apple.negative":"反例",
    "apple.testSummary":"{passed} / {total} 项通过", "apple.improved":"改善", "apple.regressed":"回归", "apple.savedHistory":"查看验证记录",
    "apple.emptyResult":"保存并验证后，这里会逐项显示真实的检索结果。", "apple.details":"事件记录与技术详情", "apple.detailsClose":"关闭面板",
    "apple.notice":"部分改进记录无法读取，下面仍保留可用的记录。", "apple.cancelled":"已回滚的记录保留用于审计。需要修改时，请从任务反馈创建新修订。",
    "apple.revise":"进入改进工作台", "apple.connectionCopy":"连接状态与历史记录分开展示。配置存在并不代表工具当前在线。",
    "apple.dataLocal":"真实项目 · 本地数据", "apple.stepsLabel":"经验改进步骤", "apple.backList":"返回任务列表", "apple.savedReadOnly":"已保存的验证证据",
    "apple.openDraft":"继续修改", "apple.feedbackRequired":"先记录一次明确反馈，再开始修订。", "apple.currentFeedback":"当前反馈",
    "apple.projects":"选择项目", "apple.mobileNav":"Impact 导航", "apple.theme":"切换深浅色", "apple.searchLabel":"搜索任务",
  },
  en: {
    "apple.lessons":"Lessons in this task", "apple.taskCounts":"{searches} searches · {exposures} exposures",
    "apple.rated":"Explicitly rated exposures",
    "apple.overview":"Impact overview", "apple.runs":"Tasks", "apple.improve":"Improvements", "apple.verify":"Verification",
    "apple.overviewCopy":"See whether lessons help, and what to improve next.", "apple.runsCopy":"Keep the evidence and your judgment together.",
    "apple.improveCopy":"Start with specific feedback and make the lesson more useful.", "apple.verifyCopy":"Keep evidence for every change.",
    "apple.all":"All", "apple.pending":"Needs feedback", "apple.attention":"Needs attention", "apple.search":"Search tasks or tools", "apple.loaded":"{count} loaded tasks",
    "apple.noMatches":"No matching records.", "apple.allTime":"All time", "apple.project":"Current project", "apple.connections":"Observation connections",
    "apple.confirm":"Review evidence", "apple.edit":"Edit lesson", "apple.test":"Verify & apply", "apple.nextEdit":"Edit this lesson", "apple.nextTest":"Next: verification",
    "apple.back":"Back", "apple.unsaved":"Drafts stay in this tab when navigating. Reloading with unsaved edits will prompt you.",
    "apple.original":"Base version", "apple.draft":"Proposed draft", "apple.examples":"Examples and counterexamples", "apple.saved":"Draft saved",
    "apple.sources":"Where the problem occurred", "apple.sourceCopy":"Review the task context before deciding what to change.", "apple.openRun":"Open source task",
    "apple.issue":"Check this lesson’s applicability", "apple.issueCount":"{count} judgments on the same version", "apple.miss":"A lesson was missing when needed",
    "apple.missCopy":"Query text was not retained. Add the intended query, review it, and save an evaluation example.", "apple.reviewMiss":"Add a retrieval example",
    "apple.pendingWork":"To review", "apple.completedWork":"Completed", "apple.noWork":"No improvements to review", "apple.noWorkCopy":"Record task feedback to collect issues and revisions here.",
    "apple.noRevisions":"No lesson verification records yet", "apple.noRevisionsCopy":"Create a revision from feedback, add positive and negative queries, and inspect real retrieval results.",
    "apple.inspect":"Lesson details", "apple.inspectCopy":"Only content matching the recorded version is shown.", "apple.inspectMissing":"This historical version is unavailable. Its identity remains visible; current content is not substituted for historical evidence.",
    "apple.query":"What was being searched", "apple.queryMissing":"Query text was not retained. Retrieval events and lesson version evidence remain available.",
    "apple.noQuery":"No search event has been recorded.", "apple.runName":"{client} · {date}", "apple.runUnnamed":"Task title not recorded", "apple.runCopy":"{searches} searches · {exposures} lesson exposures · {feedback} feedback events",
    "apple.openImprove":"Review & improve", "apple.pendingTitle":"Some lesson exposures still need feedback", "apple.pendingCopy":"Review the task and add your judgment.",
    "apple.followTitle":"Keep observing real use", "apple.followCopy":"Use subsequent task feedback to decide whether a lesson needs changing.", "apple.done":"Completed improvements",
    "apple.waiting":"Awaiting evidence", "apple.later":"Later tasks for this exact version", "apple.helpful":"Rated helpful", "apple.boundary":"Retrieval success does not prove task improvement. Follow-up evidence must match the applied version.",
    "apple.recent":"Recent tasks", "apple.viewAll":"View all", "apple.change":"Lesson changes", "apple.retrieval":"Retrieval & examples",
    "apple.changed":"Changed", "apple.failed":"Failed", "apple.noChanges":"No examples match this filter.", "apple.positive":"positive", "apple.negative":"negative",
    "apple.testSummary":"{passed} / {total} passed", "apple.improved":"Improved", "apple.regressed":"Regressed", "apple.savedHistory":"View verification",
    "apple.emptyResult":"Save and test to see actual retrieval results for each example.", "apple.details":"Events & technical details", "apple.detailsClose":"Close panel",
    "apple.notice":"Some improvement records could not be read. Available records are retained below.", "apple.cancelled":"Rolled-back records remain available for audit. Start a new revision from task feedback to make another change.",
    "apple.revise":"Open improvements", "apple.connectionCopy":"Connection status is separate from past evidence. Configuration does not prove the tool is currently online.",
    "apple.dataLocal":"Real project · Local data", "apple.stepsLabel":"Lesson improvement steps", "apple.backList":"Back to tasks", "apple.savedReadOnly":"Saved verification evidence",
    "apple.openDraft":"Continue editing", "apple.feedbackRequired":"Record an explicit judgment before creating a revision.", "apple.currentFeedback":"Current feedback",
    "apple.projects":"Select project", "apple.mobileNav":"Impact navigation", "apple.theme":"Toggle appearance", "apple.searchLabel":"Search tasks",
  },
} as const;
