export const REVISION_TEXT = {
  en: {
    "revision.open": "Review this lesson", "revision.title": "Refine an experience", "revision.close": "Close",
    "revision.intro": "Start with what happened. Test a focused change, then decide whether to apply it.",
    "revision.history": "Experience revisions", "revision.empty": "No revisions in this project yet. Open a real task in Impact and review a lesson that appeared there.",
    "revision.loading": "Loading…", "revision.busy": "Working…", "revision.saved": "Draft saved locally.",
    "revision.sourceFeedback": "Source judgment", "revision.latestFeedback": "Latest rating in this task",
    "revision.feedback": "1 · What happened in this task?", "revision.helpful": "Helpful", "revision.irrelevant": "Irrelevant",
    "revision.harmful": "Harmful", "revision.should_have_matched": "Should have matched", "revision.unrated": "No rating recorded",
    "revision.feedbackSaved": "Feedback recorded. You can now draft a revision.", "revision.feedbackRequired": "Record feedback above before saving a revision.",
    "revision.edit": "2 · Propose a focused change", "revision.reason": "Why does this experience need to change?",
    "revision.field.title": "Title", "revision.field.context": "When it applies", "revision.field.mistake": "Pitfall", "revision.field.fix": "What to do", "revision.field.tags": "Tags (comma separated)",
    "revision.before": "Compare with the original", "revision.stale": "The lesson has changed since the source or draft. Acceptance checks the current saved version and will never overwrite later edits.",
    "revision.global": "This is a global lesson. Applying this change affects every project that uses it.",
    "revision.tests": "3 · Check where it belongs", "revision.positive": "Should surface · one query per line", "revision.negative": "Should stay out · one query per line",
    "revision.testHelp": "At least one query in each group. Checks use local keyword search and a frozen set of lessons: the target must appear in the first five positive results and be absent from the first five negative results. This does not test model behavior.",
    "revision.save": "Save draft", "revision.evaluate": "Save & test", "revision.accept": "Apply tested revision", "revision.reject": "Reject draft", "revision.rollback": "Roll back this revision",
    "revision.draft": "Draft", "revision.rejected": "Rejected", "revision.accepted": "Applied", "revision.rolled_back": "Rolled back",
    "revision.baseline": "Original", "revision.candidate": "Proposed", "revision.pass": "Pass", "revision.fail": "Fail", "revision.query": "Query / expectation",
    "revision.include": "Should surface", "revision.exclude": "Should stay out", "revision.tested": "Checked against frozen lessons:",
    "revision.dirty": "Unsaved changes — save and test again before applying.", "revision.activity": "Later evidence for this revision",
    "revision.activityEmpty": "No task evidence for this exact revision yet. Passing the examples does not prove it helped a real task.",
    "revision.activityUnavailable": "Task evidence could not be read. The revision receipt is still available.", "revision.exposures": "times surfaced",
    "revision.source": "Source task", "revision.version": "Source version", "revision.appliedAt": "Applied", "revision.revertedAt": "Rolled back",
    "revision.local": "Reasons, example queries and the frozen corpus stay in this project. The lesson change and rollback receipt are stored with the lesson.",
    "revision.notEditable": "This lesson is missing, retired or graduated. Its feedback can be recorded, but it cannot be revised here.",
  },
  zh: {
    "revision.open": "复盘这条经验", "revision.title": "让经验更准确", "revision.close": "关闭",
    "revision.intro": "从这次任务发生的事出发，测试一处明确的改进，再决定是否应用。",
    "revision.history": "经验修订", "revision.empty": "本项目还没有修订记录。打开观测中的真实任务，从出现过的经验开始复盘。",
    "revision.loading": "正在加载…", "revision.busy": "正在处理…", "revision.saved": "草稿已保存在本项目。",
    "revision.sourceFeedback": "来源反馈", "revision.latestFeedback": "本任务的最新评价",
    "revision.feedback": "1 · 这次任务中，它有帮助吗？", "revision.helpful": "有帮助", "revision.irrelevant": "不相关", "revision.harmful": "有误导",
    "revision.should_have_matched": "应该出现", "revision.unrated": "尚未评价", "revision.feedbackSaved": "反馈已记录，可以开始修订经验。", "revision.feedbackRequired": "请先在上方记录反馈，再保存修订草稿。",
    "revision.edit": "2 · 提出一处明确的改进", "revision.reason": "为什么需要修改这条经验？",
    "revision.field.title": "标题", "revision.field.context": "适用场景", "revision.field.mistake": "容易犯的错误", "revision.field.fix": "建议做法", "revision.field.tags": "标签（用逗号分隔）",
    "revision.before": "对照原有内容", "revision.stale": "经验已不再是来源或草稿对应的版本。应用时会校验当前内容，避免覆盖后续修改。",
    "revision.global": "这是一条全局经验，应用修改会影响使用它的所有项目。",
    "revision.tests": "3 · 验证适用边界", "revision.positive": "应该出现 · 每行一个查询", "revision.negative": "不该出现 · 每行一个查询",
    "revision.testHelp": "两组至少各一个例子。使用本地关键词检索和固定的经验集合：正例要求目标经验进入前五条，反例要求不进入前五条。这项检查不验证模型行为。",
    "revision.save": "保存草稿", "revision.evaluate": "保存并测试", "revision.accept": "应用已测试的修订", "revision.reject": "拒绝草稿", "revision.rollback": "回滚这次修订",
    "revision.draft": "草稿", "revision.rejected": "已拒绝", "revision.accepted": "已应用", "revision.rolled_back": "已回滚",
    "revision.baseline": "原有内容", "revision.candidate": "修订内容", "revision.pass": "通过", "revision.fail": "未通过", "revision.query": "查询 / 预期",
    "revision.include": "应该出现", "revision.exclude": "不该出现", "revision.tested": "固定语料中的经验数：",
    "revision.dirty": "有未保存的修改，请重新保存并测试后再应用。", "revision.activity": "这个版本的后续任务证据",
    "revision.activityEmpty": "暂时没有这个确切版本的任务证据。例子测试通过，还不能证明它帮助了真实任务。",
    "revision.activityUnavailable": "暂时无法读取任务证据，修订回执仍然可用。", "revision.exposures": "次出现",
    "revision.source": "来源任务", "revision.version": "来源版本", "revision.appliedAt": "应用时间", "revision.revertedAt": "回滚时间",
    "revision.local": "修改理由、测试查询和固定语料保留在本项目；经验内容和回滚回执随经验存储。",
    "revision.notEditable": "这条经验已不存在、已停用或已毕业。可以记录反馈，但不能在这里修订。",
  },
} as const;
