export const RUN_EVIDENCE_TEXT = {
  en: {
    "focus.title": "This task",
    "focus.found": "Were these lessons useful?",
    "focus.quiet": "No lesson search recorded",
    "focus.empty": "No lessons surfaced this time",
    "focus.noAction": "Nothing to review here. Continue your task.",
    "focus.prompt": "A quick judgment helps identify what to improve. Select a lesson to read it.",
    "focus.lesson": "Lesson",
    "focus.helpful": "Helpful",
    "focus.irrelevant": "Not relevant",
    "focus.harmful": "Harmful",
    "focus.received": "Feedback saved",
    "focus.diagnostic": "Search needs attention",
    "focus.more": "More lessons",
    "focus.progress": "Your feedback in progress",
    "focus.followup": "Applied version seen in later tasks",
    "focus.waitingUse": "Applied · waiting for new task evidence",
    "focus.openRevision": "View tests and next step",
    "focus.feedbackNext": "Feedback saved. Open a lesson to propose and test a change.",
    "focus.details": "View evidence and technical details",
    "focus.saving": "Saving…",
    "focus.retry": "Not saved. Please retry.",
    "focus.inspectFirst": "The original text is unavailable here. Open the lesson before giving feedback.",

    "value.awaiting_completion": "Awaiting completion",
    "evidence.title": "From this task to better guidance",
    "evidence.intro": "Follow recorded evidence, review a lesson, then inspect its tested revision and later use.",
    "evidence.search": "Search", "evidence.exposure": "Lessons surfaced", "evidence.feedback": "Feedback", "evidence.validation": "Validation",
    "evidence.searched": "Searches were recorded. Check diagnostics and the returned lessons below.",
    "evidence.noSearch": "No search recorded. This does not tell us whether the task needed one.",
    "evidence.surfaced": "Lessons appeared in results; this does not establish adoption.",
    "evidence.noExposure": "No lesson exposure recorded; this alone is not a confirmed miss.",
    "evidence.rated": "Judgments are recorded in the timeline. Inspect their source and revision.",
    "evidence.noFeedback": "No judgment recorded. Review a surfaced lesson to say whether it helped.",
    "evidence.validated": "Check outcomes are recorded separately from lesson usefulness.",
    "evidence.noValidation": "No validation receipt recorded; this does not mean tests failed.",
    "evidence.diagnostics": "Search diagnostics recorded. Inspect the search events before interpreting empty results",
    "evidence.lessons": "Review the lessons from this task",
    "evidence.noLessons": "A real exposure or scoped feedback event is needed to review a specific lesson.",
    "evidence.revisions": "Revisions originating from this task",
    "evidence.noRevisions": "No linked revision yet. Review a lesson above to record feedback and test a change.",
    "evidence.unavailable": "Some revision records could not be read. Available records are shown; missing records are not counted as zero.",
    "evidence.sourceVersion": "Observed version", "evidence.tests": "Offline retrieval checks", "evidence.later": "Later runs for the applied version (up to 20)",
    "evidence.passed": "Passed", "evidence.failed": "Failed", "evidence.untested": "Not tested",
    "evidence.limit": "Open a revision to compare before/after checks, inspect later feedback, or review its rollback receipt. Passing retrieval checks does not prove task improvement. Awaiting completion means no end event has arrived, not proof that the Agent is still running.",
  },
  zh: {
    "focus.title": "本次任务",
    "focus.found": "这些经验帮上忙了吗？",
    "focus.quiet": "本轮未记录经验检索",
    "focus.empty": "本轮没有展示经验",
    "focus.noAction": "这里暂无待反馈内容，继续处理任务即可。",
    "focus.prompt": "选一下是否有用；点击经验名称可查看内容。",
    "focus.lesson": "经验",
    "focus.helpful": "有用",
    "focus.irrelevant": "不相关",
    "focus.harmful": "有害",
    "focus.received": "反馈已保存",
    "focus.diagnostic": "检索有一项提示",
    "focus.more": "其他经验",
    "focus.progress": "反馈后的改进",
    "focus.followup": "应用版本已出现在后续任务",
    "focus.waitingUse": "已应用，等待后续任务验证",
    "focus.openRevision": "查看测试与下一步",
    "focus.feedbackNext": "反馈已保存。打开经验可提出修改并测试。",
    "focus.details": "查看证据与技术详情",
    "focus.saving": "正在保存…",
    "focus.retry": "未保存，请重试。",
    "focus.inspectFirst": "这里无法展示当时的经验内容，请先打开查看再反馈。",

    "value.awaiting_completion": "等待结束记录",
    "evidence.title": "从本次任务到经验改进",
    "evidence.intro": "沿着真实证据检查经验，进入修订与测试，再查看修改后的使用反馈。",
    "evidence.search": "检索", "evidence.exposure": "经验曝光", "evidence.feedback": "反馈", "evidence.validation": "验证",
    "evidence.searched": "已记录检索，请结合下方诊断与返回的经验判断效果。",
    "evidence.noSearch": "未记录检索，不能据此判断本轮是否需要检索。",
    "evidence.surfaced": "经验出现在结果中，不代表已被采用。",
    "evidence.noExposure": "未记录经验曝光，仅凭这一点不能确认漏检。",
    "evidence.rated": "时间线中已有判断，请检查反馈来源与经验版本。",
    "evidence.noFeedback": "尚无判断，可检查本轮曝光的经验并记录是否有用。",
    "evidence.validated": "已记录验证结果；验证通过与经验有用是两类证据。",
    "evidence.noValidation": "未记录验证凭据，不代表测试失败。",
    "evidence.diagnostics": "检索产生了诊断信息，请先检查检索事件再解释空结果",
    "evidence.lessons": "检查本轮经验",
    "evidence.noLessons": "需要真实曝光或带明确作用域的反馈事件，才能检查具体经验。",
    "evidence.revisions": "由本轮任务发起的修订",
    "evidence.noRevisions": "暂无关联修订。可从上方经验入口记录反馈并测试修改。",
    "evidence.unavailable": "部分修订记录无法读取。仍展示可用记录，不将缺失记录当作零。",
    "evidence.sourceVersion": "当时曝光的版本", "evidence.tests": "离线检索测试", "evidence.later": "应用版本的后续任务（最多 20 条）",
    "evidence.passed": "通过", "evidence.failed": "未通过", "evidence.untested": "尚未测试",
    "evidence.limit": "打开修订可比较修改前后的测试、查看后续反馈或回滚凭据。检索测试通过不等于任务效果改善。“等待结束记录”仅说明尚无结束事件，不保证 Agent 进程仍在运行。",
  },
} as const;
