export const WEB_TEXT = {
      en: {
        "app.subtitle": "review console",
        "nav.review": "Review",
        "nav.library": "Library",
        "nav.learning": "Learning",
        "nav.embeddings": "Embeddings",
        "action.refresh": "Refresh",
        "action.add": "Add",
        "action.hideSidebar": "Hide sidebar",
        "action.showSidebar": "Show sidebar",
        "action.hideQueue": "Hide queue pane",
        "action.showQueue": "Show queue pane",
        "action.showWorkspace": "Projects & sessions",
        "action.hideWorkspace": "Hide projects & sessions",
        "action.deleteSession": "Delete selected",
        "action.renameSession": "Rename selected",
        "action.cleanDeletedCandidates": "Clear deleted candidates",
        "action.useProvider": "Use provider",
        "action.reindexProject": "Reindex project",
        "action.reindexGlobal": "Reindex global",
        "action.markLearned": "Mark learned",
        "action.learned": "Learned",
        "action.saveDraft": "Save draft",
        "action.approveForAgent": "Approve for agent",
        "action.approveAndAddLearning": "Approve and add to Learning",
        "action.addToLearning": "Add to Learning",
        "action.removeFromLearning": "Remove from Learning",
        "action.rename": "Rename",
        "action.expandCollection": "Expand {title}",
        "action.collapseCollection": "Collapse {title}",
        "action.moveEarlier": "Move earlier",
        "action.moveLater": "Move later",
        "action.previousChapter": "Previous",
        "action.nextChapter": "Next",
        "section.sessions": "sessions",
        "session.status.active": "active",
        "session.status.closed": "closed",
        "qualityWarning.clearTrigger": "The context does not clearly say when this trap applies.",
        "qualityWarning.specificMistake": "The mistake is not specific enough.",
        "qualityWarning.actionableFix": "The fix is not actionable enough.",
        "qualityWarning.futureReuse": "Future reuse is unclear.",
        "qualityWarning.projectScope": "The scope is too loose for a project trap.",
        "qualityWarning.durableTrap": "This reads like a broad reminder rather than a durable trap.",
        "qualityWarning.evidence": "This candidate has no evidence.",
        "placeholder.projectPath": "/path/to/project",
        "placeholder.endpoint": "http://127.0.0.1:11434",
        "placeholder.model": "qwen3-embedding:0.6b",
        "title.candidateInbox": "candidate inbox",
        "title.candidateDetail": "candidate detail",
        "title.trapLibrary": "trap library",
        "title.trapDetail": "trap detail",
        "title.learningInsights": "learning insights",
        "title.learningDetail": "learning detail",
        "title.standaloneInsights": "standalone notes",
        "title.embeddings": "embeddings",
        "title.embeddingDetail": "semantic search detail",
        "title.currentProfile": "current profile",
        "title.projectEmbeddings": "project embeddings",
        "title.globalEmbeddings": "global embeddings",
        "title.storedProfiles": "stored profiles",
        "title.providerSetup": "provider setup",
        "title.reindex": "reindex",
        "title.evidence": "evidence",
        "title.sourceCoverage": "source coverage",
        "title.sourceContext": "source background",
        "title.possibleConflicts": "possible conflicts",
        "title.before": "Before",
        "title.after": "After",
        "tab.inbox": "Inbox {count}",
        "tab.reviewed": "Reviewed {count}",
        "meta.noProject": "no project selected",
        "meta.noSession": "no session selected",
        "meta.sessionCounts": "{goal} / {pending} pending, {reviewed} reviewed",
        "meta.libraryCounts": "{shown} shown / {loaded} loaded / {sort}",
        "meta.learningCounts": "{count} insights / {consulted} learned",
        "meta.learningVisibleCounts": "{shown} shown / {count} insights / {consulted} learned",
        "meta.collectionProgress": "{learned} of {count} learned",
        "meta.chapterPosition": "{position} / {count}",
        "meta.embeddingCounts": "{provider} / project {projectFresh}/{projectTotal} fresh / global {globalFresh}/{globalTotal} fresh",
        "meta.embeddingDetail": "{profile} / {state}",
        "meta.selectCandidate": "select a candidate",
        "meta.selectTrap": "select a trap",
        "meta.selectProject": "select a project",
        "meta.selectInsight": "select a learning insight",
        "empty.noProjects": "No projects",
        "empty.noSessions": "No sessions",
        "empty.noPending": "No pending candidates",
        "empty.noReviewed": "No reviewed candidates",
        "empty.noTrapMatches": "No traps match this view",
        "empty.noTrapSelected": "No trap selected",
        "empty.loadingTrapDetails": "Loading trap details",
        "empty.noCandidateSelected": "No candidate selected",
        "empty.noEvidence": "No evidence",
        "empty.noData": "No data",
        "empty.noTraps": "No traps",
        "empty.noProfiles": "No stored profiles",
        "empty.noLearningInsightsTitle": "No learning insights yet",
        "empty.noLearningInsights": "Traps are not copied here automatically. Learning insights appear only when a reviewed Phase 2 candidate is intentionally shelved for study.",
        "empty.noLearningMatchesTitle": "No notes match these filters",
        "empty.noLearningMatches": "Clear or change the learning filters to see the rest of the library.",
        "label.learningGenerationPrompt": "Recommended request for an agent",
        "prompt.learningGeneration": "Turn this source into study material. First inventory every substantive source unit. Route core knowledge and examples into study insights, preserve background facts in collection context, and exclude only page chrome or non-content with a reason. Explain the material with an ASCII flow diagram and an easy-to-understand example. Show me the draft and coverage account before saving it to Codetrap.",
        "coverageBrief.unknown": "source not audited",
        "coverageBrief.incomplete": "source pending · {unresolved_units} missing",
        "coverageBrief.complete": "source audited",
        "coverageBrief.curated_subset": "source audited · {skipped_units} not included",
        "coverageBrief.sampled": "sample audited",
        "coverage.unknown": "coverage not audited",
        "coverage.incomplete": "in progress {covered_units}/{learn_units}",
        "coverage.complete": "audited {covered_units}/{learn_units}",
        "coverage.curated_subset": "curated · {covered_units} covered / {skipped_units} skipped",
        "coverage.sampled": "sample audited {covered_units}/{learn_units}",
        "coverage.unknownDetail": "This legacy collection has no source-unit inventory, so the app cannot verify whether anything was omitted.",
        "coverage.incompleteDetail": "{covered_units} of {learn_units} learnable source units have reached the library. Unresolved units remain visible below.",
        "coverage.completeDetail": "Every inventoried source unit intended for learning has reached the library; none were silently omitted.",
        "coverage.curated_subsetDetail": "Every inventoried unit is accounted for. {skipped_units} units were intentionally excluded with recorded reasons.",
        "coverage.sampledDetail": "Every unit in the captured sample is accounted for. Content outside that sample was not audited and is not claimed as complete.",
        "coverage.reviewUnits": "Review {count} source units",
        "action.viewTrap": "View trap",
        "action.clearFilters": "Clear filters",
        "action.save": "Save",
        "action.accept": "Accept",
        "action.reject": "Reject",
        "action.cancel": "Cancel",
        "action.confirmReject": "Reject and suppress",
        "action.undoSuppression": "Allow future proposals",
        "action.acceptAnyway": "Accept anyway",
        "action.supersede": "Supersede",
        "placeholder.searchTraps": "Search title, context, mistake, fix, tags",
        "placeholder.searchLearning": "Search notes, collections, tags, sources",
        "placeholder.anyModule": "any module",
        "placeholder.anyOwner": "any owner",
        "placeholder.supersedesId": "supersedes id",
        "label.scope": "Scope",
        "label.status": "Status",
        "label.learningScope": "Learning library scope",
        "label.sourceType": "Source type",
        "label.category": "Category",
        "label.sort": "Sort",
        "label.module": "Module",
        "label.owner": "Owner",
        "label.provider": "Provider",
        "label.endpoint": "Endpoint",
        "label.model": "Model",
        "label.dimensions": "Dimensions",
        "label.profileId": "Profile id",
        "label.available": "Available",
        "label.setupAction": "Next action",
        "label.fresh": "Fresh",
        "label.stale": "Stale",
        "label.missing": "Missing",
        "label.total": "Total",
        "label.count": "Count",
        "label.title": "Title",
        "label.summary": "Summary",
        "label.severity": "Severity",
        "label.tags": "Tags",
        "label.pathGlobs": "Path globs",
        "label.context": "Context",
        "label.mistake": "Mistake",
        "label.fix": "Fix",
        "label.rejectReason": "Reason (optional)",
        "label.created": "Created",
        "label.updated": "Updated",
        "label.stateKey": "State key",
        "label.supersedes": "Supersedes",
        "label.validFrom": "Valid from",
        "label.validUntil": "Valid until",
        "label.body": "Learning note",
        "label.sourceRefs": "Sources",
        "label.sourceUnits": "Source unit IDs",
        "label.sourceFingerprint": "Source fingerprint",
        "label.learningStatus": "Learning status",
        "label.shelvedAt": "Shelved at",
        "label.consultedCount": "Times learned",
        "label.lastConsultedAt": "Last learned at",
        "metric.visibleTraps": "Current traps",
        "metric.needsValidation": "Needs validation",
        "metric.neverUseful": "Never marked useful",
        "metric.activeProvider": "Active provider",
        "metric.activeProfile": "Active profile",
        "metric.projectFresh": "Project fresh",
        "metric.globalFresh": "Global fresh",
        "metric.healthAll": "show the complete current view",
        "metric.validationWindow": "not validated in the last {days} days",
        "metric.neverUsefulDetail": "no useful feedback recorded",
        "option.projectGlobal": "project + global",
        "option.allCategories": "all categories",
        "sort.updated": "recently updated",
        "sort.severity": "severity",
        "sort.hits": "hit count",
        "sort.category": "category",
        "sort.title": "title",
        "sortLabel.updated": "recent first",
        "sortLabel.severity": "severity first",
        "sortLabel.hits": "hits first",
        "sortLabel.category": "category sort",
        "sortLabel.title": "title sort",
        "pill.hits": "{count} hits",
        "pill.consulted": "learned",
        "pill.learned": "learned",
        "pill.notLearned": "not learned",
        "pill.pending": "{count} pending",
        "pill.candidates": "{count} candidates",
        "pill.accepted": "{count} accepted",
        "pill.warnings": "{count} warnings",
        "pill.quality": "quality {score}",
        "pill.conflict": "conflict {status}",
        "pill.action": "action {action}",
        "review.pending": "pending review",
        "reviewSummary.pending": "{count} pending candidate(s)",
        "reviewSummary.sessions": "{count} session(s)",
        "reviewSummary.quality": "{high} high quality / {edit} need edit",
        "review.rejected": "rejected",
        "review.approved": "approved — editing invalidates this approval",
        "review.destinationCommitted": "added to {destination}",
        "action.approve": "Approve",
        "action.reapprove": "Re-approve",
        "action.rollback": "Roll back",
        "confirm.rollback": "Roll back this commit? The trap is deleted and the candidate returns to review.",
        "confirm.removeFromLearning": "Remove this insight from Learning and return it to review?",
        "status.candidateApproved": "Approved; an agent may now commit this revision",
        "status.candidateRolledBack": "Rolled back; the trap was deleted and the candidate is back in review",
        "receipt.title": "Trust receipt",
        "receipt.executor": "executor: {executor} (declared, not verified)",
        "receipt.scope": "authorized scope: {scope}",
        "review.accepted": "accepted -> trap #{id}",
        "review.acceptedDeleted": "accepted -> trap #{id} deleted",
        "review.acceptedLinkMissing": "accepted -> trap link missing",
        "embedding.available": "available",
        "embedding.unavailable": "unavailable",
        "embedding.notConfigured": "not configured",
        "embedding.noProfile": "no active profile",
        "embedding.activeProfile": "active profile",
        "embedding.profileNeedsReindex": "profile needs reindex",
        "status.refreshed": "Refreshed",
        "status.candidateSaved": "Candidate saved",
        "status.candidateRejected": "Candidate rejected and suppressed; it will not be proposed again",
        "status.suppressionUndone": "Suppression removed; this lesson may be proposed again in the future",
        "status.externalChanges": "Updated from changes made outside this page",
        "status.externalChangesDeferred": "External changes detected; your unsaved draft was preserved",
        "status.refreshDeferred": "Refresh paused; save or finish the current draft first",
        "status.candidateAccepted": "Candidate accepted",
        "status.possibleConflict": "Possible conflict found",
        "status.supersedesRequired": "Supersedes id is required",
        "status.openedTrap": "Opened trap #{id}",
        "status.trapNotInLibrary": "Trap #{id} is not in the current library",
        "status.sessionDeleted": "Session deleted",
        "status.sessionRenamed": "Session renamed",
        "status.deletedCandidatesCleaned": "Deleted candidate links cleared",
        "status.embeddingProviderSaved": "Embedding provider saved",
        "status.embeddingsReindexed": "Embeddings reindexed: {generated} generated, {skipped} skipped",
        "status.invalidDimensions": "Dimensions must be a positive integer",
        "status.insightConsulted": "Learning insight marked as learned",
        "status.insightAdded": "Learning insight added to the shelf",
        "status.insightRemoved": "Learning insight removed from the shelf and returned to review",
        "status.collectionUpdated": "Learning collection updated",
        "status.collectionReordered": "Learning order updated",
        "error.sessionExpired": "This tab expired after the Web server restarted. Close it and use the newest tab opened by codetrap web --open.",
        "hint.acceptUsesCurrentDraft": "Accept uses the current draft.",
        "hint.unsavedDraftAccepted": "Unsaved edits will be accepted.",
        "hint.jinaEnv": "Jina uses JINA_API_KEY from the environment; the web console does not save API keys.",
        "hint.reindexAfterSwitch": "Reindex project or global embeddings before semantic/hybrid search can use the active profile.",
        "hint.markLearnedExplicit": "Opening a note is read-only. This button explicitly records that you studied it.",
        "hint.learnedRecorded": "This insight has already been marked learned; opening it remains read-only.",
        "hint.insightReviewActions": "Save edits, approve for an agent, or approve and add this revision to Learning now.",
        "prompt.deleteSession": "Delete session {id}?",
        "prompt.renameSession": "New name for this session",
        "prompt.renameCollection": "New name for this learning collection",
        "dialog.rejectTitle": "Reject this candidate?",
        "dialog.rejectCandidate": "Candidate: {title}",
        "dialog.rejectScope": "This also suppresses the exact lesson fingerprint across this project, so an equivalent candidate will not be proposed again. It does not affect other lessons.",
        "dialog.rejectUndo": "After rejecting, you can allow future proposals again from the receipt.",
        "value.project": "project",
        "value.global": "global",
        "value.ollama": "Ollama",
        "value.jina": "Jina",
        "value.active": "active",
        "value.all": "all",
        "value.archived": "archived",
        "value.superseded": "superseded",
        "value.proposed": "proposed",
        "value.accepted": "accepted",
        "value.rejected": "rejected",
        "value.accepted_missing": "accepted missing",
        "value.warning": "warning",
        "value.error": "error",
        "value.critical": "critical",
        "value.api": "api",
        "value.database": "database",
        "value.auth": "auth",
        "value.convention": "convention",
        "value.security": "security",
        "value.performance": "performance",
        "value.bug": "bug",
        "value.other": "other",
        "value.pitfall_trap": "pitfall trap",
        "value.unclassified": "unclassified",
        "value.project_convention": "project convention",
        "value.docs_guidance": "docs guidance",
        "value.search_eval_case": "search eval case",
        "value.insight": "learning insight",
        "value.skill_candidate": "skill candidate",
        "value.none": "none",
        "value.possible": "possible",
        "value.confirmed": "confirmed",
        "value.accept": "accept",
        "value.edit": "edit",
        "value.supersede": "supersede",
        "value.archive_old": "archive old",
        "value.manual": "manual",
        "value.conversation": "conversation",
        "value.commit": "commit",
        "value.issue": "issue",
        "value.test_failure": "test failure",
        "value.article": "article",
        "value.documentation": "documentation",
        "value.paper": "paper",
        "value.video": "video",
        "value.course": "course",
        "value.allProjects": "all projects",
        "value.currentProject": "current project",
        "value.anyStatus": "any status",
        "value.anySourceType": "any source",
        "value.anyTag": "any tag",
        "value.autoGrouped": "auto-grouped",
        "value.full_source": "full source",
        "value.sampled": "sampled source",
        "value.covered": "covered",
        "value.skipped": "skipped",
        "value.unresolved": "unresolved",
        "value.thisInsight": "this insight",
        "value.legacyCollection": "legacy collection",
        "value.never": "never",
        "value.learned": "learned",
        "value.notLearned": "not learned",
        "value.noSource": "No source recorded",
      },
      zh: {
        "app.subtitle": "复盘控制台",
        "nav.review": "审核",
        "nav.library": "库",
        "nav.learning": "学习",
        "nav.embeddings": "嵌入",
        "action.refresh": "刷新",
        "action.add": "添加",
        "action.hideSidebar": "隐藏侧边栏",
        "action.showSidebar": "显示侧边栏",
        "action.hideQueue": "隐藏队列栏",
        "action.showQueue": "显示队列栏",
        "action.showWorkspace": "项目与会话",
        "action.hideWorkspace": "收起项目与会话",
        "action.deleteSession": "删除所选",
        "action.renameSession": "重命名所选",
        "action.cleanDeletedCandidates": "清除已删除候选",
        "action.useProvider": "使用提供方",
        "action.reindexProject": "重建项目索引",
        "action.reindexGlobal": "重建全局索引",
        "action.markLearned": "标记已学习",
        "action.learned": "已学习",
        "action.saveDraft": "保存草稿",
        "action.approveForAgent": "仅批准，交给 Agent",
        "action.approveAndAddLearning": "批准并加入学习架",
        "action.addToLearning": "加入学习架",
        "action.removeFromLearning": "从学习架撤回",
        "action.rename": "重命名",
        "action.expandCollection": "展开合集：{title}",
        "action.collapseCollection": "收起合集：{title}",
        "action.moveEarlier": "向前移动",
        "action.moveLater": "向后移动",
        "action.previousChapter": "上一篇",
        "action.nextChapter": "下一篇",
        "section.sessions": "会话",
        "session.status.active": "进行中",
        "session.status.closed": "已关闭",
        "qualityWarning.clearTrigger": "上下文没有清楚说明此陷阱何时适用。",
        "qualityWarning.specificMistake": "错误描述不够具体。",
        "qualityWarning.actionableFix": "修复方案还不够可执行。",
        "qualityWarning.futureReuse": "尚不清楚这条经验以后如何复用。",
        "qualityWarning.projectScope": "对于项目级陷阱，适用范围过于宽泛。",
        "qualityWarning.durableTrap": "候选内容更像宽泛提醒，不像可长期复用的陷阱。",
        "qualityWarning.evidence": "这个候选还没有证据。",
        "placeholder.projectPath": "/项目/路径",
        "placeholder.endpoint": "http://127.0.0.1:11434",
        "placeholder.model": "qwen3-embedding:0.6b",
        "title.candidateInbox": "候选收件箱",
        "title.candidateDetail": "候选详情",
        "title.trapLibrary": "陷阱库",
        "title.trapDetail": "陷阱详情",
        "title.learningInsights": "学习洞察",
        "title.learningDetail": "学习详情",
        "title.standaloneInsights": "独立内容",
        "title.embeddings": "嵌入",
        "title.embeddingDetail": "语义搜索详情",
        "title.currentProfile": "当前 profile",
        "title.projectEmbeddings": "项目嵌入",
        "title.globalEmbeddings": "全局嵌入",
        "title.storedProfiles": "已存 profile",
        "title.providerSetup": "提供方设置",
        "title.reindex": "重建索引",
        "title.evidence": "证据",
        "title.sourceCoverage": "来源覆盖",
        "title.sourceContext": "文章来源背景",
        "title.possibleConflicts": "可能冲突",
        "title.before": "修改前",
        "title.after": "修改后",
        "tab.inbox": "待审 {count}",
        "tab.reviewed": "已审 {count}",
        "meta.noProject": "未选择项目",
        "meta.noSession": "未选择会话",
        "meta.sessionCounts": "{goal} / {pending} 个待审，{reviewed} 个已审",
        "meta.libraryCounts": "显示 {shown} / 已加载 {loaded} / {sort}",
        "meta.learningCounts": "{count} 条洞察 / {consulted} 条已学习",
        "meta.learningVisibleCounts": "显示 {shown} / 共 {count} 条 / {consulted} 条已学习",
        "meta.collectionProgress": "已学习 {learned} / {count}",
        "meta.chapterPosition": "第 {position} / {count} 条",
        "meta.embeddingCounts": "{provider} / 项目 {projectFresh}/{projectTotal} fresh / 全局 {globalFresh}/{globalTotal} fresh",
        "meta.embeddingDetail": "{profile} / {state}",
        "meta.selectCandidate": "选择一个候选",
        "meta.selectTrap": "选择一个陷阱",
        "meta.selectProject": "选择一个项目",
        "meta.selectInsight": "选择一条学习洞察",
        "empty.noProjects": "没有项目",
        "empty.noSessions": "没有会话",
        "empty.noPending": "没有待审候选",
        "empty.noReviewed": "没有已审候选",
        "empty.noTrapMatches": "没有匹配的陷阱",
        "empty.noTrapSelected": "未选择陷阱",
        "empty.loadingTrapDetails": "正在加载陷阱详情",
        "empty.noCandidateSelected": "未选择候选",
        "empty.noEvidence": "没有证据",
        "empty.noData": "没有数据",
        "empty.noTraps": "没有陷阱",
        "empty.noProfiles": "没有已存 profile",
        "empty.noLearningInsightsTitle": "还没有学习洞察",
        "empty.noLearningInsights": "陷阱不会自动复制到这里。只有经过审核、并明确归档为学习内容的 Phase 2 候选才会出现在这里。",
        "empty.noLearningMatchesTitle": "没有符合筛选条件的内容",
        "empty.noLearningMatches": "清除或修改学习筛选条件，即可查看其余内容。",
        "label.learningGenerationPrompt": "推荐发送给 Agent 的提示词",
        "prompt.learningGeneration": "帮我把这份资料整理成学习内容。先盘点所有实质性的来源单元：核心知识和案例进入学习章节，背景事实保存在合集背景中，只有网页外壳或非正文内容才可以写明理由后排除；用ASCII流程图结合通俗易懂的例子讲解。先把草稿和覆盖清单给我审核，确认后再写入 Codetrap。",
        "coverageBrief.unknown": "原文未核对",
        "coverageBrief.incomplete": "原文待补 · 缺 {unresolved_units} 项",
        "coverageBrief.complete": "原文已核对",
        "coverageBrief.curated_subset": "原文已核对 · {skipped_units} 项未收录",
        "coverageBrief.sampled": "样本已核对",
        "coverage.unknown": "未核对覆盖",
        "coverage.incomplete": "整理中 {covered_units}/{learn_units}",
        "coverage.complete": "已核对 {covered_units}/{learn_units}",
        "coverage.curated_subset": "精选 · 已覆盖 {covered_units} / 跳过 {skipped_units}",
        "coverage.sampled": "抽样核对 {covered_units}/{learn_units}",
        "coverage.unknownDetail": "这个旧合集没有来源单元清单，因此系统无法验证是否存在遗漏。",
        "coverage.incompleteDetail": "计划学习的 {learn_units} 个来源单元中，已有 {covered_units} 个进入学习库；待处理单元会继续显示在下方。",
        "coverage.completeDetail": "清单中计划学习的来源单元都已进入学习库，没有静默遗漏。",
        "coverage.curated_subsetDetail": "清单中的每个单元都有去向，其中 {skipped_units} 个单元已写明理由后主动跳过。",
        "coverage.sampledDetail": "本次采集到的样本单元都已有去向；样本以外的原始内容没有经过核对，因此不会声称全文完整。",
        "coverage.reviewUnits": "查看 {count} 个来源单元",
        "action.viewTrap": "查看陷阱",
        "action.clearFilters": "清除筛选",
        "action.save": "保存",
        "action.accept": "接受",
        "action.reject": "拒绝",
        "action.cancel": "取消",
        "action.confirmReject": "拒绝并抑制",
        "action.undoSuppression": "允许今后再次提出",
        "action.acceptAnyway": "仍然接受",
        "action.supersede": "标记取代",
        "placeholder.searchTraps": "搜索标题、上下文、错误、修复、标签",
        "placeholder.searchLearning": "搜索内容、合集、标签和来源",
        "placeholder.anyModule": "任意模块",
        "placeholder.anyOwner": "任意负责人",
        "placeholder.supersedesId": "被取代的 id",
        "label.scope": "范围",
        "label.status": "状态",
        "label.learningScope": "学习库范围",
        "label.sourceType": "来源类型",
        "label.category": "分类",
        "label.sort": "排序",
        "label.module": "模块",
        "label.owner": "负责人",
        "label.provider": "提供方",
        "label.endpoint": "端点",
        "label.model": "模型",
        "label.dimensions": "维度",
        "label.profileId": "Profile id",
        "label.available": "可用",
        "label.setupAction": "下一步",
        "label.fresh": "最新",
        "label.stale": "过期",
        "label.missing": "缺失",
        "label.total": "总数",
        "label.count": "数量",
        "label.title": "标题",
        "label.summary": "摘要",
        "label.severity": "严重度",
        "label.tags": "标签",
        "label.pathGlobs": "路径规则",
        "label.context": "上下文",
        "label.mistake": "错误",
        "label.fix": "修复",
        "label.rejectReason": "拒绝原因（可选）",
        "label.created": "创建时间",
        "label.updated": "更新时间",
        "label.stateKey": "状态键",
        "label.supersedes": "取代",
        "label.validFrom": "生效开始",
        "label.validUntil": "生效结束",
        "label.body": "学习内容",
        "label.sourceRefs": "资料来源",
        "label.sourceUnits": "来源单元 ID",
        "label.sourceFingerprint": "来源指纹",
        "label.learningStatus": "学习状态",
        "label.shelvedAt": "加入时间",
        "label.consultedCount": "学习次数",
        "label.lastConsultedAt": "最近学习时间",
        "metric.visibleTraps": "当前陷阱",
        "metric.needsValidation": "需要复核",
        "metric.neverUseful": "从未标记有用",
        "metric.activeProvider": "当前提供方",
        "metric.activeProfile": "当前 profile",
        "metric.projectFresh": "项目 fresh",
        "metric.globalFresh": "全局 fresh",
        "metric.healthAll": "显示当前完整列表",
        "metric.validationWindow": "最近 {days} 天没有验证",
        "metric.neverUsefulDetail": "还没有有用反馈记录",
        "option.projectGlobal": "项目 + 全局",
        "option.allCategories": "全部分类",
        "sort.updated": "最近更新",
        "sort.severity": "严重度",
        "sort.hits": "查看次数",
        "sort.category": "分类",
        "sort.title": "标题",
        "sortLabel.updated": "最近优先",
        "sortLabel.severity": "严重度优先",
        "sortLabel.hits": "查看次数优先",
        "sortLabel.category": "按分类排序",
        "sortLabel.title": "按标题排序",
        "pill.hits": "{count} 次查看",
        "pill.consulted": "已学习",
        "pill.learned": "已学习",
        "pill.notLearned": "未学习",
        "pill.pending": "{count} 个待审",
        "pill.candidates": "{count} 个候选",
        "pill.accepted": "{count} 个已接受",
        "pill.warnings": "{count} 个警告",
        "pill.quality": "质量 {score}",
        "pill.conflict": "冲突 {status}",
        "pill.action": "建议 {action}",
        "review.pending": "待审核",
        "reviewSummary.pending": "{count} 个待审候选",
        "reviewSummary.sessions": "{count} 个会话",
        "reviewSummary.quality": "{high} 个高质量 / {edit} 个需编辑",
        "review.rejected": "已拒绝",
        "review.approved": "已批准 — 编辑将使该批准失效",
        "review.destinationCommitted": "已加入{destination}",
        "action.approve": "批准",
        "action.reapprove": "重新批准",
        "action.rollback": "回滚",
        "confirm.rollback": "回滚此次提交？陷阱将被删除，候选返回评审队列。",
        "confirm.removeFromLearning": "从学习架撤回这条洞察，并让它返回审核队列吗？",
        "status.candidateApproved": "已批准；代理现在可以提交此修订版本",
        "status.candidateRolledBack": "已回滚；陷阱已删除，候选返回评审队列",
        "receipt.title": "信任回执",
        "receipt.executor": "执行者：{executor}（声明值，未经验证）",
        "receipt.scope": "授权范围：{scope}",
        "review.accepted": "已接受 -> 陷阱 #{id}",
        "review.acceptedDeleted": "已接受 -> 陷阱 #{id} 已删除",
        "review.acceptedLinkMissing": "已接受 -> 缺少陷阱链接",
        "embedding.available": "可用",
        "embedding.unavailable": "不可用",
        "embedding.notConfigured": "未配置",
        "embedding.noProfile": "没有当前 profile",
        "embedding.activeProfile": "当前 profile",
        "embedding.profileNeedsReindex": "profile 需要重建索引",
        "status.refreshed": "已刷新",
        "status.candidateSaved": "候选已保存",
        "status.candidateRejected": "候选已拒绝并抑制，不会再次提出",
        "status.suppressionUndone": "已取消抑制；今后可以再次提出这条经验",
        "status.externalChanges": "已同步页面外部产生的更改",
        "status.externalChangesDeferred": "检测到外部更改；你的未保存草稿已保留",
        "status.refreshDeferred": "已暂停刷新；请先保存或处理当前草稿",
        "status.candidateAccepted": "候选已接受",
        "status.possibleConflict": "发现可能冲突",
        "status.supersedesRequired": "需要填写被取代的 id",
        "status.openedTrap": "已打开陷阱 #{id}",
        "status.trapNotInLibrary": "当前陷阱库里没有陷阱 #{id}",
        "status.sessionDeleted": "会话已删除",
        "status.sessionRenamed": "会话已重命名",
        "status.deletedCandidatesCleaned": "已清除删除候选链接",
        "status.embeddingProviderSaved": "嵌入提供方已保存",
        "status.embeddingsReindexed": "嵌入索引已重建：生成 {generated}，跳过 {skipped}",
        "status.invalidDimensions": "维度必须是正整数",
        "status.insightConsulted": "已将学习洞察标记为已学习",
        "status.insightAdded": "学习洞察已加入学习架",
        "status.insightRemoved": "学习洞察已从学习架撤回并返回审核队列",
        "status.collectionUpdated": "学习合集已更新",
        "status.collectionReordered": "学习顺序已更新",
        "error.sessionExpired": "Web 服务已重启，此旧标签页的访问凭证已失效。请关闭它，使用 codetrap web --open 新打开的标签页。",
        "hint.acceptUsesCurrentDraft": "接受时会使用当前草稿。",
        "hint.unsavedDraftAccepted": "未保存编辑也会随接受生效。",
        "hint.jinaEnv": "Jina 使用环境变量 JINA_API_KEY；网页控制台不会保存 API key。",
        "hint.reindexAfterSwitch": "重建项目或全局嵌入后，语义/混合搜索才能使用当前 profile。",
        "hint.markLearnedExplicit": "打开内容只会阅读；点击此按钮才会明确记录你已经学习。",
        "hint.learnedRecorded": "这条洞察已经标记为已学习；再次打开只会阅读，不会重复计数。",
        "hint.insightReviewActions": "可先保存修改、仅批准交给 Agent，或直接批准并将当前版本加入学习架。",
        "prompt.deleteSession": "删除会话 {id}？",
        "prompt.renameSession": "输入新的会话名称",
        "prompt.renameCollection": "输入新的学习合集名称",
        "dialog.rejectTitle": "要拒绝这个候选吗？",
        "dialog.rejectCandidate": "候选：{title}",
        "dialog.rejectScope": "此操作还会在当前项目中抑制这条经验的精确指纹，因此内容等价的候选不会再次出现；其他经验不受影响。",
        "dialog.rejectUndo": "拒绝后，可以在操作回执中重新允许今后提出这条经验。",
        "value.project": "项目",
        "value.global": "全局",
        "value.ollama": "Ollama",
        "value.jina": "Jina",
        "value.active": "有效",
        "value.all": "全部",
        "value.archived": "已归档",
        "value.superseded": "已取代",
        "value.proposed": "待提议",
        "value.accepted": "已接受",
        "value.rejected": "已拒绝",
        "value.accepted_missing": "接受记录缺失",
        "value.warning": "警告",
        "value.error": "错误",
        "value.critical": "严重",
        "value.api": "API",
        "value.database": "数据库",
        "value.auth": "认证",
        "value.convention": "约定",
        "value.security": "安全",
        "value.performance": "性能",
        "value.bug": "缺陷",
        "value.other": "其他",
        "value.pitfall_trap": "错误陷阱",
        "value.unclassified": "未分类候选",
        "value.project_convention": "项目约定",
        "value.docs_guidance": "文档指引",
        "value.search_eval_case": "搜索评测用例",
        "value.insight": "学习洞察",
        "value.skill_candidate": "技能候选",
        "value.none": "无",
        "value.possible": "可能",
        "value.confirmed": "确认",
        "value.accept": "接受",
        "value.edit": "编辑",
        "value.supersede": "取代",
        "value.archive_old": "归档旧项",
        "value.manual": "手动",
        "value.conversation": "对话",
        "value.commit": "提交",
        "value.issue": "Issue",
        "value.test_failure": "测试失败",
        "value.article": "文章",
        "value.documentation": "技术文档",
        "value.paper": "论文",
        "value.video": "视频",
        "value.course": "课程",
        "value.allProjects": "全部项目",
        "value.currentProject": "当前项目",
        "value.anyStatus": "全部状态",
        "value.anySourceType": "全部来源",
        "value.anyTag": "全部标签",
        "value.autoGrouped": "自动整理",
        "value.full_source": "完整来源",
        "value.sampled": "抽样来源",
        "value.covered": "已覆盖",
        "value.skipped": "已跳过",
        "value.unresolved": "待处理",
        "value.thisInsight": "本条内容",
        "value.legacyCollection": "旧合集",
        "value.never": "从未",
        "value.learned": "已学习",
        "value.notLearned": "未学习",
        "value.noSource": "未记录来源",
      }
    } as const;

export type WebLocale = keyof typeof WEB_TEXT;
export type WebTextKey = keyof typeof WEB_TEXT["en"];

export const WEB_TEXT_JSON = JSON.stringify(WEB_TEXT);
