export const WEB_TEXT = {
      en: {
        "app.subtitle": "review console",
        "nav.review": "Review",
        "nav.library": "Library",
        "nav.insights": "Insights",
        "action.refresh": "Refresh",
        "action.add": "Add",
        "action.hideSidebar": "Hide sidebar",
        "action.showSidebar": "Show sidebar",
        "action.hideQueue": "Hide queue pane",
        "action.showQueue": "Show queue pane",
        "action.deleteSession": "Delete",
        "action.cleanDeletedCandidates": "Clear deleted candidates",
        "section.sessions": "sessions",
        "placeholder.projectPath": "/path/to/project",
        "title.candidateInbox": "candidate inbox",
        "title.candidateDetail": "candidate detail",
        "title.trapLibrary": "trap library",
        "title.trapDetail": "trap detail",
        "title.growthInsights": "growth insights",
        "title.insightDetail": "insight detail",
        "title.recentTraps": "recent traps",
        "title.mostViewed": "most viewed",
        "title.recentHighSeverity": "recent high severity",
        "title.evidence": "evidence",
        "title.possibleConflicts": "possible conflicts",
        "title.before": "Before",
        "title.after": "After",
        "tab.inbox": "Inbox {count}",
        "tab.reviewed": "Reviewed {count}",
        "meta.noProject": "no project selected",
        "meta.noSession": "no session selected",
        "meta.sessionCounts": "{goal} / {pending} pending, {reviewed} reviewed",
        "meta.libraryCounts": "{shown} shown / {loaded} loaded / {sort}",
        "meta.insightCounts": "{count} traps / {status} status",
        "meta.selectCandidate": "select a candidate",
        "meta.selectTrap": "select a trap",
        "meta.selectProject": "select a project",
        "empty.noProjects": "No projects",
        "empty.noSessions": "No sessions",
        "empty.noPending": "No pending candidates",
        "empty.noReviewed": "No reviewed candidates",
        "empty.noTrapMatches": "No traps match this view",
        "empty.noTrapSelected": "No trap selected",
        "empty.loadingTrapDetails": "Loading trap details",
        "empty.noCandidateSelected": "No candidate selected",
        "empty.noEvidence": "No evidence",
        "empty.noData": "No data",
        "empty.noTraps": "No traps",
        "action.viewTrap": "View trap",
        "action.clearFilters": "Clear filters",
        "action.save": "Save",
        "action.accept": "Accept",
        "action.reject": "Reject",
        "action.acceptAnyway": "Accept anyway",
        "action.supersede": "Supersede",
        "placeholder.searchTraps": "Search title, context, mistake, fix, tags",
        "placeholder.anyModule": "any module",
        "placeholder.anyOwner": "any owner",
        "placeholder.supersedesId": "supersedes id",
        "label.scope": "Scope",
        "label.status": "Status",
        "label.category": "Category",
        "label.sort": "Sort",
        "label.module": "Module",
        "label.owner": "Owner",
        "label.title": "Title",
        "label.severity": "Severity",
        "label.tags": "Tags",
        "label.pathGlobs": "Path globs",
        "label.context": "Context",
        "label.mistake": "Mistake",
        "label.fix": "Fix",
        "label.created": "Created",
        "label.updated": "Updated",
        "label.stateKey": "State key",
        "label.supersedes": "Supersedes",
        "label.validFrom": "Valid from",
        "label.validUntil": "Valid until",
        "metric.loadedTraps": "Loaded traps",
        "metric.confirmedTraps": "Confirmed traps",
        "metric.highSeverity": "High severity",
        "metric.topCategory": "Top category",
        "metric.focusArea": "Focus area",
        "metric.mostViewed": "Most viewed",
        "metric.currentFilters": "current filters",
        "metric.selectedScope": "selected scope",
        "metric.errorCritical": "error + critical",
        "metric.repeatedPattern": "repeated pattern",
        "metric.largestPattern": "largest pattern",
        "metric.module": "module",
        "metric.tag": "tag",
        "metric.noHits": "no hits yet",
        "insight.categories": "categories",
        "insight.modules": "modules",
        "insight.tags": "tags",
        "insight.severityMix": "severity mix",
        "option.projectGlobal": "project + global",
        "option.allCategories": "all categories",
        "sort.updated": "recently updated",
        "sort.severity": "severity",
        "sort.hits": "hit count",
        "sort.category": "category",
        "sort.title": "title",
        "sortLabel.updated": "recent first",
        "sortLabel.severity": "severity first",
        "sortLabel.hits": "hits first",
        "sortLabel.category": "category sort",
        "sortLabel.title": "title sort",
        "pill.hits": "{count} hits",
        "pill.candidates": "{count} candidates",
        "pill.accepted": "{count} accepted",
        "pill.warnings": "{count} warnings",
        "pill.quality": "quality {score}",
        "pill.conflict": "conflict {status}",
        "pill.action": "action {action}",
        "review.pending": "pending review",
        "review.rejected": "rejected",
        "review.accepted": "accepted -> trap #{id}",
        "review.acceptedDeleted": "accepted -> trap #{id} deleted",
        "review.acceptedLinkMissing": "accepted -> trap link missing",
        "status.refreshed": "Refreshed",
        "status.candidateSaved": "Candidate saved",
        "status.candidateRejected": "Candidate rejected",
        "status.candidateAccepted": "Candidate accepted",
        "status.possibleConflict": "Possible conflict found",
        "status.supersedesRequired": "Supersedes id is required",
        "status.openedTrap": "Opened trap #{id}",
        "status.trapNotInLibrary": "Trap #{id} is not in the current library",
        "status.sessionDeleted": "Session deleted",
        "status.deletedCandidatesCleaned": "Deleted candidate links cleared",
        "prompt.rejectReason": "Reject reason",
        "prompt.deleteSession": "Delete session {id}?",
        "value.project": "project",
        "value.global": "global",
        "value.active": "active",
        "value.all": "all",
        "value.archived": "archived",
        "value.superseded": "superseded",
        "value.proposed": "proposed",
        "value.accepted": "accepted",
        "value.rejected": "rejected",
        "value.accepted_missing": "accepted missing",
        "value.warning": "warning",
        "value.error": "error",
        "value.critical": "critical",
        "value.api": "api",
        "value.database": "database",
        "value.auth": "auth",
        "value.convention": "convention",
        "value.security": "security",
        "value.performance": "performance",
        "value.bug": "bug",
        "value.other": "other",
        "value.none": "none",
        "value.possible": "possible",
        "value.confirmed": "confirmed",
        "value.accept": "accept",
        "value.edit": "edit",
        "value.supersede": "supersede",
        "value.archive_old": "archive old",
        "value.manual": "manual",
        "value.conversation": "conversation",
        "value.commit": "commit",
        "value.issue": "issue",
        "value.test_failure": "test failure",
        "value.article": "article",
      },
      zh: {
        "app.subtitle": "复盘控制台",
        "nav.review": "审核",
        "nav.library": "库",
        "nav.insights": "洞察",
        "action.refresh": "刷新",
        "action.add": "添加",
        "action.hideSidebar": "隐藏侧边栏",
        "action.showSidebar": "显示侧边栏",
        "action.hideQueue": "隐藏队列栏",
        "action.showQueue": "显示队列栏",
        "action.deleteSession": "删除",
        "action.cleanDeletedCandidates": "清除已删除候选",
        "section.sessions": "会话",
        "placeholder.projectPath": "/项目/路径",
        "title.candidateInbox": "候选收件箱",
        "title.candidateDetail": "候选详情",
        "title.trapLibrary": "陷阱库",
        "title.trapDetail": "陷阱详情",
        "title.growthInsights": "成长洞察",
        "title.insightDetail": "洞察详情",
        "title.recentTraps": "最近陷阱",
        "title.mostViewed": "查看最多",
        "title.recentHighSeverity": "最近高严重度",
        "title.evidence": "证据",
        "title.possibleConflicts": "可能冲突",
        "title.before": "修改前",
        "title.after": "修改后",
        "tab.inbox": "待审 {count}",
        "tab.reviewed": "已审 {count}",
        "meta.noProject": "未选择项目",
        "meta.noSession": "未选择会话",
        "meta.sessionCounts": "{goal} / {pending} 个待审，{reviewed} 个已审",
        "meta.libraryCounts": "显示 {shown} / 已加载 {loaded} / {sort}",
        "meta.insightCounts": "{count} 条陷阱 / 状态 {status}",
        "meta.selectCandidate": "选择一个候选",
        "meta.selectTrap": "选择一个陷阱",
        "meta.selectProject": "选择一个项目",
        "empty.noProjects": "没有项目",
        "empty.noSessions": "没有会话",
        "empty.noPending": "没有待审候选",
        "empty.noReviewed": "没有已审候选",
        "empty.noTrapMatches": "没有匹配的陷阱",
        "empty.noTrapSelected": "未选择陷阱",
        "empty.loadingTrapDetails": "正在加载陷阱详情",
        "empty.noCandidateSelected": "未选择候选",
        "empty.noEvidence": "没有证据",
        "empty.noData": "没有数据",
        "empty.noTraps": "没有陷阱",
        "action.viewTrap": "查看陷阱",
        "action.clearFilters": "清除筛选",
        "action.save": "保存",
        "action.accept": "接受",
        "action.reject": "拒绝",
        "action.acceptAnyway": "仍然接受",
        "action.supersede": "标记取代",
        "placeholder.searchTraps": "搜索标题、上下文、错误、修复、标签",
        "placeholder.anyModule": "任意模块",
        "placeholder.anyOwner": "任意负责人",
        "placeholder.supersedesId": "被取代的 id",
        "label.scope": "范围",
        "label.status": "状态",
        "label.category": "分类",
        "label.sort": "排序",
        "label.module": "模块",
        "label.owner": "负责人",
        "label.title": "标题",
        "label.severity": "严重度",
        "label.tags": "标签",
        "label.pathGlobs": "路径规则",
        "label.context": "上下文",
        "label.mistake": "错误",
        "label.fix": "修复",
        "label.created": "创建时间",
        "label.updated": "更新时间",
        "label.stateKey": "状态键",
        "label.supersedes": "取代",
        "label.validFrom": "生效开始",
        "label.validUntil": "生效结束",
        "metric.loadedTraps": "已加载陷阱",
        "metric.confirmedTraps": "确认陷阱",
        "metric.highSeverity": "高严重度",
        "metric.topCategory": "最高分类",
        "metric.focusArea": "关注区域",
        "metric.mostViewed": "查看最多",
        "metric.currentFilters": "当前筛选",
        "metric.selectedScope": "选中范围",
        "metric.errorCritical": "error + critical",
        "metric.repeatedPattern": "重复模式",
        "metric.largestPattern": "最大模式",
        "metric.module": "模块",
        "metric.tag": "标签",
        "metric.noHits": "还没有查看记录",
        "insight.categories": "分类",
        "insight.modules": "模块",
        "insight.tags": "标签",
        "insight.severityMix": "严重度分布",
        "option.projectGlobal": "项目 + 全局",
        "option.allCategories": "全部分类",
        "sort.updated": "最近更新",
        "sort.severity": "严重度",
        "sort.hits": "查看次数",
        "sort.category": "分类",
        "sort.title": "标题",
        "sortLabel.updated": "最近优先",
        "sortLabel.severity": "严重度优先",
        "sortLabel.hits": "查看次数优先",
        "sortLabel.category": "按分类排序",
        "sortLabel.title": "按标题排序",
        "pill.hits": "{count} 次查看",
        "pill.candidates": "{count} 个候选",
        "pill.accepted": "{count} 个已接受",
        "pill.warnings": "{count} 个警告",
        "pill.quality": "质量 {score}",
        "pill.conflict": "冲突 {status}",
        "pill.action": "建议 {action}",
        "review.pending": "待审核",
        "review.rejected": "已拒绝",
        "review.accepted": "已接受 -> 陷阱 #{id}",
        "review.acceptedDeleted": "已接受 -> 陷阱 #{id} 已删除",
        "review.acceptedLinkMissing": "已接受 -> 缺少陷阱链接",
        "status.refreshed": "已刷新",
        "status.candidateSaved": "候选已保存",
        "status.candidateRejected": "候选已拒绝",
        "status.candidateAccepted": "候选已接受",
        "status.possibleConflict": "发现可能冲突",
        "status.supersedesRequired": "需要填写被取代的 id",
        "status.openedTrap": "已打开陷阱 #{id}",
        "status.trapNotInLibrary": "当前陷阱库里没有陷阱 #{id}",
        "status.sessionDeleted": "会话已删除",
        "status.deletedCandidatesCleaned": "已清除删除候选链接",
        "prompt.rejectReason": "拒绝原因",
        "prompt.deleteSession": "删除会话 {id}？",
        "value.project": "项目",
        "value.global": "全局",
        "value.active": "有效",
        "value.all": "全部",
        "value.archived": "已归档",
        "value.superseded": "已取代",
        "value.proposed": "待提议",
        "value.accepted": "已接受",
        "value.rejected": "已拒绝",
        "value.accepted_missing": "接受记录缺失",
        "value.warning": "警告",
        "value.error": "错误",
        "value.critical": "严重",
        "value.api": "API",
        "value.database": "数据库",
        "value.auth": "认证",
        "value.convention": "约定",
        "value.security": "安全",
        "value.performance": "性能",
        "value.bug": "缺陷",
        "value.other": "其他",
        "value.none": "无",
        "value.possible": "可能",
        "value.confirmed": "确认",
        "value.accept": "接受",
        "value.edit": "编辑",
        "value.supersede": "取代",
        "value.archive_old": "归档旧项",
        "value.manual": "手动",
        "value.conversation": "对话",
        "value.commit": "提交",
        "value.issue": "Issue",
        "value.test_failure": "测试失败",
        "value.article": "文章",
      }
    } as const;

export type WebLocale = keyof typeof WEB_TEXT;
export type WebTextKey = keyof typeof WEB_TEXT["en"];

export const WEB_TEXT_JSON = JSON.stringify(WEB_TEXT);
