export const WEB_TEXT = {
      en: {
        "app.subtitle": "review console",
        "nav.review": "Review",
        "nav.library": "Library",
        "nav.learning": "Learning",
        "nav.embeddings": "Embeddings",
        "action.refresh": "Refresh",
        "action.add": "Add",
        "action.hideSidebar": "Hide sidebar",
        "action.showSidebar": "Show sidebar",
        "action.hideQueue": "Hide queue pane",
        "action.showQueue": "Show queue pane",
        "action.showWorkspace": "Projects & sessions",
        "action.hideWorkspace": "Hide projects & sessions",
        "action.deleteSession": "Delete selected",
        "action.cleanDeletedCandidates": "Clear deleted candidates",
        "action.useProvider": "Use provider",
        "action.reindexProject": "Reindex project",
        "action.reindexGlobal": "Reindex global",
        "action.markLearned": "Mark learned",
        "section.sessions": "sessions",
        "session.status.active": "active",
        "session.status.closed": "closed",
        "qualityWarning.clearTrigger": "The context does not clearly say when this trap applies.",
        "qualityWarning.specificMistake": "The mistake is not specific enough.",
        "qualityWarning.actionableFix": "The fix is not actionable enough.",
        "qualityWarning.futureReuse": "Future reuse is unclear.",
        "qualityWarning.projectScope": "The scope is too loose for a project trap.",
        "qualityWarning.durableTrap": "This reads like a broad reminder rather than a durable trap.",
        "qualityWarning.evidence": "This candidate has no evidence.",
        "placeholder.projectPath": "/path/to/project",
        "placeholder.endpoint": "http://127.0.0.1:11434",
        "placeholder.model": "qwen3-embedding:0.6b",
        "title.candidateInbox": "candidate inbox",
        "title.candidateDetail": "candidate detail",
        "title.trapLibrary": "trap library",
        "title.trapDetail": "trap detail",
        "title.learningInsights": "learning insights",
        "title.learningDetail": "learning detail",
        "title.embeddings": "embeddings",
        "title.embeddingDetail": "semantic search detail",
        "title.currentProfile": "current profile",
        "title.projectEmbeddings": "project embeddings",
        "title.globalEmbeddings": "global embeddings",
        "title.storedProfiles": "stored profiles",
        "title.providerSetup": "provider setup",
        "title.reindex": "reindex",
        "title.evidence": "evidence",
        "title.possibleConflicts": "possible conflicts",
        "title.before": "Before",
        "title.after": "After",
        "tab.inbox": "Inbox {count}",
        "tab.reviewed": "Reviewed {count}",
        "meta.noProject": "no project selected",
        "meta.noSession": "no session selected",
        "meta.sessionCounts": "{goal} / {pending} pending, {reviewed} reviewed",
        "meta.libraryCounts": "{shown} shown / {loaded} loaded / {sort}",
        "meta.learningCounts": "{count} insights / {consulted} learned",
        "meta.embeddingCounts": "{provider} / project {projectFresh}/{projectTotal} fresh / global {globalFresh}/{globalTotal} fresh",
        "meta.embeddingDetail": "{profile} / {state}",
        "meta.selectCandidate": "select a candidate",
        "meta.selectTrap": "select a trap",
        "meta.selectProject": "select a project",
        "meta.selectInsight": "select a learning insight",
        "empty.noProjects": "No projects",
        "empty.noSessions": "No sessions",
        "empty.noPending": "No pending candidates",
        "empty.noReviewed": "No reviewed candidates",
        "empty.noTrapMatches": "No traps match this view",
        "empty.noTrapSelected": "No trap selected",
        "empty.loadingTrapDetails": "Loading trap details",
        "empty.noCandidateSelected": "No candidate selected",
        "empty.noEvidence": "No evidence",
        "empty.noData": "No data",
        "empty.noTraps": "No traps",
        "empty.noProfiles": "No stored profiles",
        "empty.noLearningInsightsTitle": "No learning insights yet",
        "empty.noLearningInsights": "Traps are not copied here automatically. Learning insights appear only when a reviewed Phase 2 candidate is intentionally shelved for study.",
        "action.viewTrap": "View trap",
        "action.clearFilters": "Clear filters",
        "action.save": "Save",
        "action.accept": "Accept",
        "action.reject": "Reject",
        "action.acceptAnyway": "Accept anyway",
        "action.supersede": "Supersede",
        "placeholder.searchTraps": "Search title, context, mistake, fix, tags",
        "placeholder.anyModule": "any module",
        "placeholder.anyOwner": "any owner",
        "placeholder.supersedesId": "supersedes id",
        "label.scope": "Scope",
        "label.status": "Status",
        "label.category": "Category",
        "label.sort": "Sort",
        "label.module": "Module",
        "label.owner": "Owner",
        "label.provider": "Provider",
        "label.endpoint": "Endpoint",
        "label.model": "Model",
        "label.dimensions": "Dimensions",
        "label.profileId": "Profile id",
        "label.available": "Available",
        "label.setupAction": "Next action",
        "label.fresh": "Fresh",
        "label.stale": "Stale",
        "label.missing": "Missing",
        "label.total": "Total",
        "label.count": "Count",
        "label.title": "Title",
        "label.severity": "Severity",
        "label.tags": "Tags",
        "label.pathGlobs": "Path globs",
        "label.context": "Context",
        "label.mistake": "Mistake",
        "label.fix": "Fix",
        "label.created": "Created",
        "label.updated": "Updated",
        "label.stateKey": "State key",
        "label.supersedes": "Supersedes",
        "label.validFrom": "Valid from",
        "label.validUntil": "Valid until",
        "label.body": "Learning note",
        "label.shelvedAt": "Shelved at",
        "label.consultedCount": "Times learned",
        "label.lastConsultedAt": "Last learned at",
        "metric.visibleTraps": "Current traps",
        "metric.needsValidation": "Needs validation",
        "metric.neverUseful": "Never marked useful",
        "metric.activeProvider": "Active provider",
        "metric.activeProfile": "Active profile",
        "metric.projectFresh": "Project fresh",
        "metric.globalFresh": "Global fresh",
        "metric.healthAll": "show the complete current view",
        "metric.validationWindow": "not validated in the last {days} days",
        "metric.neverUsefulDetail": "no useful feedback recorded",
        "option.projectGlobal": "project + global",
        "option.allCategories": "all categories",
        "sort.updated": "recently updated",
        "sort.severity": "severity",
        "sort.hits": "hit count",
        "sort.category": "category",
        "sort.title": "title",
        "sortLabel.updated": "recent first",
        "sortLabel.severity": "severity first",
        "sortLabel.hits": "hits first",
        "sortLabel.category": "category sort",
        "sortLabel.title": "title sort",
        "pill.hits": "{count} hits",
        "pill.consulted": "learned {count} times",
        "pill.pending": "{count} pending",
        "pill.candidates": "{count} candidates",
        "pill.accepted": "{count} accepted",
        "pill.warnings": "{count} warnings",
        "pill.quality": "quality {score}",
        "pill.conflict": "conflict {status}",
        "pill.action": "action {action}",
        "review.pending": "pending review",
        "reviewSummary.pending": "{count} pending candidate(s)",
        "reviewSummary.sessions": "{count} session(s)",
        "reviewSummary.quality": "{high} high quality / {edit} need edit",
        "review.rejected": "rejected",
        "review.approved": "approved — editing invalidates this approval",
        "action.approve": "Approve",
        "action.reapprove": "Re-approve",
        "action.rollback": "Roll back",
        "confirm.rollback": "Roll back this commit? The trap is deleted and the candidate returns to review.",
        "status.candidateApproved": "Approved; an agent may now commit this revision",
        "status.candidateRolledBack": "Rolled back; the trap was deleted and the candidate is back in review",
        "receipt.title": "Trust receipt",
        "receipt.executor": "executor: {executor} (declared, not verified)",
        "receipt.scope": "authorized scope: {scope}",
        "review.accepted": "accepted -> trap #{id}",
        "review.acceptedDeleted": "accepted -> trap #{id} deleted",
        "review.acceptedLinkMissing": "accepted -> trap link missing",
        "embedding.available": "available",
        "embedding.unavailable": "unavailable",
        "embedding.notConfigured": "not configured",
        "embedding.noProfile": "no active profile",
        "embedding.activeProfile": "active profile",
        "embedding.profileNeedsReindex": "profile needs reindex",
        "status.refreshed": "Refreshed",
        "status.candidateSaved": "Candidate saved",
        "status.candidateRejected": "Candidate rejected and suppressed; it will not be proposed again",
        "status.candidateAccepted": "Candidate accepted",
        "status.possibleConflict": "Possible conflict found",
        "status.supersedesRequired": "Supersedes id is required",
        "status.openedTrap": "Opened trap #{id}",
        "status.trapNotInLibrary": "Trap #{id} is not in the current library",
        "status.sessionDeleted": "Session deleted",
        "status.deletedCandidatesCleaned": "Deleted candidate links cleared",
        "status.embeddingProviderSaved": "Embedding provider saved",
        "status.embeddingsReindexed": "Embeddings reindexed: {generated} generated, {skipped} skipped",
        "status.invalidDimensions": "Dimensions must be a positive integer",
        "status.insightConsulted": "Learning insight marked as learned",
        "hint.acceptUsesCurrentDraft": "Accept uses the current draft.",
        "hint.unsavedDraftAccepted": "Unsaved edits will be accepted.",
        "hint.jinaEnv": "Jina uses JINA_API_KEY from the environment; the web console does not save API keys.",
        "hint.reindexAfterSwitch": "Reindex project or global embeddings before semantic/hybrid search can use the active profile.",
        "hint.markLearnedExplicit": "Opening a note is read-only. This button explicitly records that you studied it.",
        "prompt.rejectReason": "Reject reason (this also suppresses the lesson project-wide)",
        "prompt.deleteSession": "Delete session {id}?",
        "value.project": "project",
        "value.global": "global",
        "value.ollama": "Ollama",
        "value.jina": "Jina",
        "value.active": "active",
        "value.all": "all",
        "value.archived": "archived",
        "value.superseded": "superseded",
        "value.proposed": "proposed",
        "value.accepted": "accepted",
        "value.rejected": "rejected",
        "value.accepted_missing": "accepted missing",
        "value.warning": "warning",
        "value.error": "error",
        "value.critical": "critical",
        "value.api": "api",
        "value.database": "database",
        "value.auth": "auth",
        "value.convention": "convention",
        "value.security": "security",
        "value.performance": "performance",
        "value.bug": "bug",
        "value.other": "other",
        "value.none": "none",
        "value.possible": "possible",
        "value.confirmed": "confirmed",
        "value.accept": "accept",
        "value.edit": "edit",
        "value.supersede": "supersede",
        "value.archive_old": "archive old",
        "value.manual": "manual",
        "value.conversation": "conversation",
        "value.commit": "commit",
        "value.issue": "issue",
        "value.test_failure": "test failure",
        "value.article": "article",
        "value.never": "never",
      },
      zh: {
        "app.subtitle": "复盘控制台",
        "nav.review": "审核",
        "nav.library": "库",
        "nav.learning": "学习",
        "nav.embeddings": "嵌入",
        "action.refresh": "刷新",
        "action.add": "添加",
        "action.hideSidebar": "隐藏侧边栏",
        "action.showSidebar": "显示侧边栏",
        "action.hideQueue": "隐藏队列栏",
        "action.showQueue": "显示队列栏",
        "action.showWorkspace": "项目与会话",
        "action.hideWorkspace": "收起项目与会话",
        "action.deleteSession": "删除所选",
        "action.cleanDeletedCandidates": "清除已删除候选",
        "action.useProvider": "使用提供方",
        "action.reindexProject": "重建项目索引",
        "action.reindexGlobal": "重建全局索引",
        "action.markLearned": "标记已学习",
        "section.sessions": "会话",
        "session.status.active": "进行中",
        "session.status.closed": "已关闭",
        "qualityWarning.clearTrigger": "上下文没有清楚说明此陷阱何时适用。",
        "qualityWarning.specificMistake": "错误描述不够具体。",
        "qualityWarning.actionableFix": "修复方案还不够可执行。",
        "qualityWarning.futureReuse": "尚不清楚这条经验以后如何复用。",
        "qualityWarning.projectScope": "对于项目级陷阱，适用范围过于宽泛。",
        "qualityWarning.durableTrap": "候选内容更像宽泛提醒，不像可长期复用的陷阱。",
        "qualityWarning.evidence": "这个候选还没有证据。",
        "placeholder.projectPath": "/项目/路径",
        "placeholder.endpoint": "http://127.0.0.1:11434",
        "placeholder.model": "qwen3-embedding:0.6b",
        "title.candidateInbox": "候选收件箱",
        "title.candidateDetail": "候选详情",
        "title.trapLibrary": "陷阱库",
        "title.trapDetail": "陷阱详情",
        "title.learningInsights": "学习洞察",
        "title.learningDetail": "学习详情",
        "title.embeddings": "嵌入",
        "title.embeddingDetail": "语义搜索详情",
        "title.currentProfile": "当前 profile",
        "title.projectEmbeddings": "项目嵌入",
        "title.globalEmbeddings": "全局嵌入",
        "title.storedProfiles": "已存 profile",
        "title.providerSetup": "提供方设置",
        "title.reindex": "重建索引",
        "title.evidence": "证据",
        "title.possibleConflicts": "可能冲突",
        "title.before": "修改前",
        "title.after": "修改后",
        "tab.inbox": "待审 {count}",
        "tab.reviewed": "已审 {count}",
        "meta.noProject": "未选择项目",
        "meta.noSession": "未选择会话",
        "meta.sessionCounts": "{goal} / {pending} 个待审，{reviewed} 个已审",
        "meta.libraryCounts": "显示 {shown} / 已加载 {loaded} / {sort}",
        "meta.learningCounts": "{count} 条洞察 / {consulted} 条已学习",
        "meta.embeddingCounts": "{provider} / 项目 {projectFresh}/{projectTotal} fresh / 全局 {globalFresh}/{globalTotal} fresh",
        "meta.embeddingDetail": "{profile} / {state}",
        "meta.selectCandidate": "选择一个候选",
        "meta.selectTrap": "选择一个陷阱",
        "meta.selectProject": "选择一个项目",
        "meta.selectInsight": "选择一条学习洞察",
        "empty.noProjects": "没有项目",
        "empty.noSessions": "没有会话",
        "empty.noPending": "没有待审候选",
        "empty.noReviewed": "没有已审候选",
        "empty.noTrapMatches": "没有匹配的陷阱",
        "empty.noTrapSelected": "未选择陷阱",
        "empty.loadingTrapDetails": "正在加载陷阱详情",
        "empty.noCandidateSelected": "未选择候选",
        "empty.noEvidence": "没有证据",
        "empty.noData": "没有数据",
        "empty.noTraps": "没有陷阱",
        "empty.noProfiles": "没有已存 profile",
        "empty.noLearningInsightsTitle": "还没有学习洞察",
        "empty.noLearningInsights": "陷阱不会自动复制到这里。只有经过审核、并明确归档为学习内容的 Phase 2 候选才会出现在这里。",
        "action.viewTrap": "查看陷阱",
        "action.clearFilters": "清除筛选",
        "action.save": "保存",
        "action.accept": "接受",
        "action.reject": "拒绝",
        "action.acceptAnyway": "仍然接受",
        "action.supersede": "标记取代",
        "placeholder.searchTraps": "搜索标题、上下文、错误、修复、标签",
        "placeholder.anyModule": "任意模块",
        "placeholder.anyOwner": "任意负责人",
        "placeholder.supersedesId": "被取代的 id",
        "label.scope": "范围",
        "label.status": "状态",
        "label.category": "分类",
        "label.sort": "排序",
        "label.module": "模块",
        "label.owner": "负责人",
        "label.provider": "提供方",
        "label.endpoint": "端点",
        "label.model": "模型",
        "label.dimensions": "维度",
        "label.profileId": "Profile id",
        "label.available": "可用",
        "label.setupAction": "下一步",
        "label.fresh": "最新",
        "label.stale": "过期",
        "label.missing": "缺失",
        "label.total": "总数",
        "label.count": "数量",
        "label.title": "标题",
        "label.severity": "严重度",
        "label.tags": "标签",
        "label.pathGlobs": "路径规则",
        "label.context": "上下文",
        "label.mistake": "错误",
        "label.fix": "修复",
        "label.created": "创建时间",
        "label.updated": "更新时间",
        "label.stateKey": "状态键",
        "label.supersedes": "取代",
        "label.validFrom": "生效开始",
        "label.validUntil": "生效结束",
        "label.body": "学习内容",
        "label.shelvedAt": "加入时间",
        "label.consultedCount": "学习次数",
        "label.lastConsultedAt": "最近学习时间",
        "metric.visibleTraps": "当前陷阱",
        "metric.needsValidation": "需要复核",
        "metric.neverUseful": "从未标记有用",
        "metric.activeProvider": "当前提供方",
        "metric.activeProfile": "当前 profile",
        "metric.projectFresh": "项目 fresh",
        "metric.globalFresh": "全局 fresh",
        "metric.healthAll": "显示当前完整列表",
        "metric.validationWindow": "最近 {days} 天没有验证",
        "metric.neverUsefulDetail": "还没有有用反馈记录",
        "option.projectGlobal": "项目 + 全局",
        "option.allCategories": "全部分类",
        "sort.updated": "最近更新",
        "sort.severity": "严重度",
        "sort.hits": "查看次数",
        "sort.category": "分类",
        "sort.title": "标题",
        "sortLabel.updated": "最近优先",
        "sortLabel.severity": "严重度优先",
        "sortLabel.hits": "查看次数优先",
        "sortLabel.category": "按分类排序",
        "sortLabel.title": "按标题排序",
        "pill.hits": "{count} 次查看",
        "pill.consulted": "已学习 {count} 次",
        "pill.pending": "{count} 个待审",
        "pill.candidates": "{count} 个候选",
        "pill.accepted": "{count} 个已接受",
        "pill.warnings": "{count} 个警告",
        "pill.quality": "质量 {score}",
        "pill.conflict": "冲突 {status}",
        "pill.action": "建议 {action}",
        "review.pending": "待审核",
        "reviewSummary.pending": "{count} 个待审候选",
        "reviewSummary.sessions": "{count} 个会话",
        "reviewSummary.quality": "{high} 个高质量 / {edit} 个需编辑",
        "review.rejected": "已拒绝",
        "review.approved": "已批准 — 编辑将使该批准失效",
        "action.approve": "批准",
        "action.reapprove": "重新批准",
        "action.rollback": "回滚",
        "confirm.rollback": "回滚此次提交？陷阱将被删除，候选返回评审队列。",
        "status.candidateApproved": "已批准；代理现在可以提交此修订版本",
        "status.candidateRolledBack": "已回滚；陷阱已删除，候选返回评审队列",
        "receipt.title": "信任回执",
        "receipt.executor": "执行者：{executor}（声明值，未经验证）",
        "receipt.scope": "授权范围：{scope}",
        "review.accepted": "已接受 -> 陷阱 #{id}",
        "review.acceptedDeleted": "已接受 -> 陷阱 #{id} 已删除",
        "review.acceptedLinkMissing": "已接受 -> 缺少陷阱链接",
        "embedding.available": "可用",
        "embedding.unavailable": "不可用",
        "embedding.notConfigured": "未配置",
        "embedding.noProfile": "没有当前 profile",
        "embedding.activeProfile": "当前 profile",
        "embedding.profileNeedsReindex": "profile 需要重建索引",
        "status.refreshed": "已刷新",
        "status.candidateSaved": "候选已保存",
        "status.candidateRejected": "候选已拒绝并抑制，不会再次提出",
        "status.candidateAccepted": "候选已接受",
        "status.possibleConflict": "发现可能冲突",
        "status.supersedesRequired": "需要填写被取代的 id",
        "status.openedTrap": "已打开陷阱 #{id}",
        "status.trapNotInLibrary": "当前陷阱库里没有陷阱 #{id}",
        "status.sessionDeleted": "会话已删除",
        "status.deletedCandidatesCleaned": "已清除删除候选链接",
        "status.embeddingProviderSaved": "嵌入提供方已保存",
        "status.embeddingsReindexed": "嵌入索引已重建：生成 {generated}，跳过 {skipped}",
        "status.invalidDimensions": "维度必须是正整数",
        "status.insightConsulted": "已将学习洞察标记为已学习",
        "hint.acceptUsesCurrentDraft": "接受时会使用当前草稿。",
        "hint.unsavedDraftAccepted": "未保存编辑也会随接受生效。",
        "hint.jinaEnv": "Jina 使用环境变量 JINA_API_KEY；网页控制台不会保存 API key。",
        "hint.reindexAfterSwitch": "重建项目或全局嵌入后，语义/混合搜索才能使用当前 profile。",
        "hint.markLearnedExplicit": "打开内容只会阅读；点击此按钮才会明确记录你已经学习。",
        "prompt.rejectReason": "拒绝原因（同时会在整个项目中抑制该经验）",
        "prompt.deleteSession": "删除会话 {id}？",
        "value.project": "项目",
        "value.global": "全局",
        "value.ollama": "Ollama",
        "value.jina": "Jina",
        "value.active": "有效",
        "value.all": "全部",
        "value.archived": "已归档",
        "value.superseded": "已取代",
        "value.proposed": "待提议",
        "value.accepted": "已接受",
        "value.rejected": "已拒绝",
        "value.accepted_missing": "接受记录缺失",
        "value.warning": "警告",
        "value.error": "错误",
        "value.critical": "严重",
        "value.api": "API",
        "value.database": "数据库",
        "value.auth": "认证",
        "value.convention": "约定",
        "value.security": "安全",
        "value.performance": "性能",
        "value.bug": "缺陷",
        "value.other": "其他",
        "value.none": "无",
        "value.possible": "可能",
        "value.confirmed": "确认",
        "value.accept": "接受",
        "value.edit": "编辑",
        "value.supersede": "取代",
        "value.archive_old": "归档旧项",
        "value.manual": "手动",
        "value.conversation": "对话",
        "value.commit": "提交",
        "value.issue": "Issue",
        "value.test_failure": "测试失败",
        "value.article": "文章",
        "value.never": "从未",
      }
    } as const;

export type WebLocale = keyof typeof WEB_TEXT;
export type WebTextKey = keyof typeof WEB_TEXT["en"];

export const WEB_TEXT_JSON = JSON.stringify(WEB_TEXT);
